@startuml Task

!include ./value/TaskId.pu
!include ./value/Title.pu
!include ./value/TaskDescription.pu
!include ./value/DoD.pu
!include ./value/TaskComment.pu
!include ./value/TaskStatus.pu

class "Task(タスク)" as Task << (R,red) RootEntity >> {
    TaskId: TaskId
    Title: Title
    Description: TaskDescription
    DoD: DoD
    Comments: TaskComment
    Status: TaskStatus
}

Task *-down- TaskId
Task *-down- Title
Task *-down- TaskDescription
Task *-down- DoD
Task "1" *-down- "*" TaskComment
Task *-down- TaskStatus

@enduml